apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ required "A valid value for product is required!" .Values.product | lower }}
  labels:
    {{- include "micro-services.labels" . | nindent 4 }}
spec:
  minReplicas: {{ .Values.replicas.min }}
  maxReplicas: {{ .Values.replicas.max }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ required "A valid value for product is required!" .Values.product | lower }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60