apiVersion: v1
kind: Service
metadata:
  name: {{ required "A valid value for product is required!" .Values.product | lower }}
  labels:
    {{- include "micro-services.labels" . | nindent 4 }}
spec:
  selector:
   {{- include "micro-services.selector-labels" . | nindent 4 }}
  ports:
    - port: {{ .Values.port }}
      name: http
      protocol: TCP
      targetPort: {{ .Values.port }}