apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.product | lower }}
  namespace: {{ .Values.team }}-{{ .Values.environment }}
  labels:
    {{- include "micro-services.labels" . | nindent 4 }}
spec:
  hosts:
  - {{ include "host.global" . | quote }}
  - {{ include "host.cluster" . | quote }}
  gateways:
  - itops/{{ .Values.team }}-gateway-alertready
  - itops/{{ .Values.team }}-gateway-naadsca
  http:
  - match:
    {{- range .Values.basePath }}
    - uri:
        prefix: {{ . | quote }}
    {{- end }}
    route:
    - destination:
        port:
          number: {{ .Values.port }}
        host: {{ required "A valid value for product is required!" .Values.product | lower }}
        subset: production
      weight: 100
